// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgebvgazjhqazequfext.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnZWJ2Z2F6amhxYXplcXVmZXh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MDU4OTgsImV4cCI6MjA2ODA4MTg5OH0.hLyfME8prr0In43-FbhcgNxWlWnXiwevEW95YThuYec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});